crmdent/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url

from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kadent.urls', namespace="kadent")),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

kadent/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from kadent import views

app_name = 'kadent'

urlpatterns = [
    # Patient
    path('patient_create', views.PatientCreate.as_view(), name='patient_create'),
    path('<int:pk>/patient_edit/',
         views.PatientUpdate.as_view(), name='patient_edit'),
    path('<int:pk>/patient_delete/',
         views.PatientDelete.as_view(), name='patient_delete'),
    path('', views.PatientList.as_view(), name='patient_list'),

    # Visit
    path('<int:pk>/visit_create/', views.VisitCreate.as_view(), name='visit_create'),
    path('<int:pk>/visit_edit/',
         views.VisitUpdate.as_view(), name='visit_edit'),
    path('<int:pk>/visit_delete/',
         views.VisitDelete.as_view(), name='visit_delete'),

     # Image
    path('<int:pk>/image_create_from_patient/',
         views.ImageCreateFromPatient.as_view(), name='image_create_from_patient'),
    path('<int:pk>/image_create_from_visit/',
         views.ImageCreateFromVisit.as_view(), name='image_create_from_visit'),
    path('<int:pk>/image_edit/',
         views.ImageUpdate.as_view(), name='image_edit'),
]

kadent/models.py
# -*- coding: utf-8 -*-
import os
from django.db import models
from django.conf import settings
from django.urls import reverse

from .validators import accepted_size, accepted_extensions
from .utils import make_thumbnail

class Patient(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(null=True, blank=True)

    def full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse('kadent:patient_edit', kwargs={'pk': self.pk})

    def __str__(self):
        return self.full_name()


class Visit(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    note = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('kadent:visit_edit', kwargs={'pk': self.pk})


class Image(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file = models.ImageField(
        upload_to='documents/',
        validators=[accepted_size, accepted_extensions]
        )
    thumbnail = models.ImageField(
        upload_to='', editable=False, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    visit = models.ForeignKey(
        Visit, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('kadent:image_edit', kwargs={'pk': self.pk})

    def filename(self):
        return os.path.basename(self.file.name)

    def save(self, *args, **kwargs):
        # save for image
        super().save(*args, **kwargs)

        make_thumbnail(self.thumbnail, self.file, (200, 200))

        # save for thumbnail
        super().save(*args, **kwargs)

kadent/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Image, Patient


ImageFormSet = modelformset_factory(Image, fields=('note', 'file'))


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['first_name', 'last_name', 'notes']
        widgets = {
            'notes': forms.Textarea(attrs={'cols': 60, 'rows': 2}),
        }

kadent/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from kadent.models import Patient, Visit, Image
from .forms import ImageFormSet, PatientForm

class PatientCreate(LoginRequiredMixin, CreateView):
    model = Patient
    fields = ['first_name', 'last_name', 'notes']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        return super(PatientCreate, self).form_valid(form)


class PatientUpdate(LoginRequiredMixin, UpdateView):
    model = Patient
    form_class = PatientForm
    template_name_suffix = '_update_form'
    def get_initial(self):
        return {'first_name': self.object.first_name,
                'last_name': self.object.last_name,
                'notes': self.object.notes}

    def get_context_data(self, **kwargs):
        context = super(PatientUpdate, self).get_context_data(**kwargs)
        context['images'] = Image.objects.filter(
            patient=self.object).order_by('-uploaded_at')
        context['visits'] = Visit.objects.filter(
            patient=self.object).order_by('-timestamp')
        return context


class PatientDelete(LoginRequiredMixin, DeleteView):
    model = Patient
    success_url = reverse_lazy('kadent:patient_list')


class PatientList(LoginRequiredMixin, ListView):
    model = Patient
    paginate_by = 50


class VisitCreate(LoginRequiredMixin, CreateView):
    model = Visit
    fields = ['note']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient_id'] = self.kwargs['pk']
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.doctor = self.request.user
        obj.patient = Patient.objects.get(id=self.kwargs['pk'])
        return super(VisitCreate, self).form_valid(form)

class VisitUpdate(LoginRequiredMixin, UpdateView):
    model = Visit
    fields = ['note']
    template_name_suffix = '_update_form'
    def get_initial(self):
        return {'note': self.object.note}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient_id'] = self.object.patient.id
        context['images'] = Image.objects.filter(visit=self.object)
        return context

class VisitDelete(LoginRequiredMixin, DeleteView):
    model = Visit
    def get_success_url(self):
        return reverse('kadent:patient_edit', args=(self.object.patient.id,))


class ImageCreateFromPatient(LoginRequiredMixin, CreateView):
    '''Create Image object when request send from PatientUpdate view'''
    model = Image
    fields = ['note', 'file']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = ImageFormSet(queryset=Image.objects.none())
        context['patient_id'] = self.kwargs['pk']
        return context

    def post(self, request, *args, **kwargs):
        counter = 0
        request.POST = request.POST.copy()
        common_note = request.POST.get('commonNote', '')
        if common_note:
            common_note = ' ' + common_note
        for img in request.FILES.getlist('images'):
            request.FILES['form-{0}-file'.format(counter)] = img
            note = request.POST[img.name]
            request.POST['form-{0}-note'.format(counter)] = note + common_note
            counter += 1
        formset = ImageFormSet(self.request.POST, self.request.FILES)
        no_errors = True
        alert_div = '<div class="alert alert-danger" role="alert">{0}</div>'
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            if no_errors:
                messages.info(
                    request, alert_div.format(
                        '<h2 class="text-center">Uwaga!</h2><h3>Wystąpiły następujące błędy:</h3>'
                    )
                )
                no_errors = False
            for errors_dicts in formset.errors:
                for val in errors_dicts.values():
                    messages.error(request, alert_div.format(val[0]))
            return redirect('kadent:image_create_from_patient', self.kwargs['pk'])

    def form_valid(self, form, **kwargs):
        patient = Patient.objects.get(id=self.kwargs['pk'])
        instances = form.save(commit=False)
        for instance in instances:
            instance.uploaded_by = self.request.user
            instance.patient = patient
        form.save()
        return redirect('kadent:patient_edit', patient.id)



class ImageCreateFromVisit(LoginRequiredMixin, CreateView):
    '''Create Image object when request send from VisitUpdate view'''
    model = Image
    fields = ['note', 'file']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = ImageFormSet(queryset=Image.objects.none())
        visit = Visit.objects.get(id=self.kwargs['pk'])
        patient = visit.patient
        context['patient_id'] = patient.id
        return context

    def post(self, request, *args, **kwargs):
        counter = 0
        request.POST = request.POST.copy()
        common_note = request.POST.get('commonNote', '')
        if common_note:
            common_note = ' ' + common_note
        for img in request.FILES.getlist('images'):
            request.FILES['form-{0}-file'.format(counter)] = img
            note = request.POST[img.name]
            request.POST['form-{0}-note'.format(counter)] = note + common_note
            counter += 1
        formset = ImageFormSet(self.request.POST, self.request.FILES)
        no_errors = True
        alert_div = '<div class="alert alert-danger" role="alert">{0}</div>'
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            if no_errors:
                messages.info(
                    request, alert_div.format(
                        '<h2 class="text-center">Uwaga!</h2><h3>Wystąpiły następujące błędy:</h3>'
                    )
                )
                no_errors = False
            for errors_dicts in formset.errors:
                for val in errors_dicts.values():
                    messages.error(request, alert_div.format(val[0]))
            return redirect('kadent:image_create_from_visit', self.kwargs['pk'])

    def form_valid(self, form, **kwargs):
        visit = Visit.objects.get(id=self.kwargs['pk'])
        patient = visit.patient
        instances = form.save(commit=False)
        for instance in instances:
            instance.uploaded_by = self.request.user
            instance.patient = patient
            instance.visit = visit
        form.save()
        return redirect('kadent:visit_edit', visit.id)


class ImageUpdate(LoginRequiredMixin, UpdateView):
    model = Image
    fields = ['note']
    template_name_suffix = '_update_form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        image = Image.objects.get(id=self.kwargs['pk'])
        context['patient_id'] = image.patient.id
        return context

    def get_initial(self):
        return {'note': self.object.note}

kadent/templates/kadent/base.html
<!DOCTYPE html>
<html lang="pl">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'kadent/style.css' %}" />
    {% block scripts %}
    {% endblock scripts %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
{% include "kadent/navbar.html" %}
    <main role="main" class="container">
    <div class="container-fluid py-2">
        {% block content %}
        {% endblock content %}

        {% block javascript %}
        {% endblock %}
    </div>
    </main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

kadent/templates/kadent/image_form.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
    {{ message|safe }}
{% endfor %}

<a href="{% url 'kadent:patient_edit' patient_id %}" class="float-right">
    <button class="btn btn-small btn-primary">Wróć do pacjenta</button>
</a>

<form id="fset" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ formset.management_form }}
    <input type="file" name="images" accept="image/*" id="multiFileBtn" multiple>
    <div id="output"></div>

    <div id="commonNote">
        <label>Wspólna notatka do wszystkich obrazów:</label>
        <input type="text" name="commonNote">
    </div>
    <input id="formSubmit" type="submit" value="Zapisz">
</form>
{% endblock content %}

{% block javascript %}
<script>
var multiFileBtn = document.getElementById('multiFileBtn');
var fset = document.getElementById('fset');
var totalForms = document.getElementById('id_form-TOTAL_FORMS');
var output = document.getElementById('output');
var formSubmit = document.getElementById('formSubmit');
var commonNote = document.getElementById('commonNote');


multiFileBtn.addEventListener('change', ()=>{
    if (multiFileBtn.files.length > 1){
        commonNote.style.display = 'block'

    }
    totalForms.value = multiFileBtn.files.length;
    for (let f of multiFileBtn.files){
        var reader = new FileReader();
        reader.addEventListener("load", function () {
            var image = new Image();
            image.height = 100;
            image.title = f.name;
            image.src = this.result;

            var newDiv = document.createElement('DIV');
            if (f.size < 1024){
                newDiv.classList.add("alert");
                newDiv.classList.add("alert-danger");
                var sizeAlert = document.createElement('h3');
                sizeAlert.innerText = 'Rozmiar pliku to: {0}B, dopuszczalne rozmiary: 1 kB - 20 MB'.replace('{0}', f.size)
                newDiv.appendChild(sizeAlert);
                formSubmit.disabled = true;
            }
            if (f.size > 20 * 1024 *1024) {
                newDiv.classList.add("alert");
                newDiv.classList.add("alert-danger");
                var sizeAlert = document.createElement('h3');
                var fileSizeInMB = Math.round((f.size / (1024 * 1024)) * 10 )/10
                sizeAlert.innerText = 'Rozmiar pliku to: {0}MB, dopuszczalne rozmiary: 1 kB - 20 MB'.replace('{0}', fileSizeInMB)
                newDiv.appendChild(sizeAlert);
                formSubmit.disabled = true;
            }
            var newFig = document.createElement('FIGURE');
            newFig.classList.add("d-inline-block");
            var newFigCaption = document.createElement('FIGCAPTION');
            newFigCaption.innerText = f.name;
            var newTextInput = document.createElement('INPUT');
            newTextInput.name = f.name;
            var hr = document.createElement('hr');

            newFig.appendChild(image);
            newFig.appendChild(newFigCaption);
            newDiv.appendChild(newFig)
            newDiv.appendChild(newTextInput)
            output.appendChild(newDiv);
            output.appendChild(hr);

        }, false);

        if (f) {
            reader.readAsDataURL(f);
        }
    }
});

multiFileBtn.addEventListener('click',()=>{
    output.innerHTML = '';
    formSubmit.disabled = false;
});

</script>
{% endblock %}

kadent/templates/kadent/image_update_form.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
<a href="{% url 'kadent:patient_edit' patient_id %}" class="float-right">
    <button class="btn btn-small btn-primary">Wróć do pacjenta</button>
</a>

<figure>
    <img src="{{ object.thumbnail.url }}" alt="{{ object.filename }}" height="200">
    <figcaption>{{ object.filename }}</figcaption>
</figure>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>
{% endblock content %}

kadent/templates/kadent/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Pacjenci</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="nazwisko" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Szukaj</button>
        </form>
        <p class="my-2 my-sm-0 text-white"><small class="p-2">zalogowano jako:</small> <b>{{ request.user }}</b></p>
        <a class="nav-link" href="{% url 'logout' %}">
            <button class="btn btn-outline-success my-2 my-sm-0 text-white">Wyloguj</button>
        </a>
    </div>
</nav>

kadent/templates/kadent/patient_confirm_delete.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
<a href="{% url 'kadent:patient_edit' patient_id %}" class="float-right">
    <button class="btn btn-small btn-primary">Wróć do pacjenta</button>
</a>

<form method="post">{% csrf_token %}
    <p>Potwierdź usunięcie pacjenta:  "{{ object }}"?</p>
    <input type="submit" value="Potwierdzam">
</form>
{% endblock content %}

kadent/templates/kadent/patient_form.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>
{% endblock content %}

kadent/templates/kadent/patient_list.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
<h1>Pacjenci</h1>
<a href="{% url 'kadent:patient_create' %}" class="float-right mb-3">
    <button class="btn btn-small btn-primary">Dodaj pacjenta</button>
</a>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">imię i nazwisko</th>

        </tr>
    </thead>
    <tbody>
        {% for patient in object_list %}
        <tr>
            <td><a href="{% url 'kadent:patient_edit' patient.id %}">{{ patient }}</a></td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock content %}

kadent/templates/kadent/patient_update_form.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
    {{ message|safe }}
{% endfor %}
<form method="post">{% csrf_token %}
<p>
    <span>
    {{ form.first_name.errors }}
    {{ form.first_name.label_tag }}
    {{ form.first_name }}
    </span>
    <span>
        {{ form.last_name.errors }}
        {{ form.last_name.label_tag }}
        {{ form.last_name }}
    </span>
</p>
<p>
    {{ form.notes.errors }}
    {{ form.notes.label_tag }}
    {{ form.notes }}
</p>
<input type="submit" value="Zapisz zmiany">
</form>

<h3 class="text-center">Wizyty</h3>
<a href="{% url 'kadent:visit_create' object.id %}">
    <button class="btn btn-small btn-primary">Dodaj wizytę do pacjenta</button>
</a>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">czas</th>
            <th scope="col">notatka</th>
            <th scope="col">doktor</th>
        </tr>
    </thead>
    <tbody>
        {% for visit in visits %}
        <tr>
            <td><a href="{% url 'kadent:visit_edit' visit.id %}">{{ visit.timestamp|date:'d.m.Y H:i' }}</a></td>
            <td><a href="{% url 'kadent:visit_edit' visit.id %}">{{ visit.note }}</a></td>
            <td><a href="{% url 'kadent:visit_edit' visit.id %}">{{ visit.doctor }}</a></td>
        </tr>
        {% endfor %}

    </tbody>
</table>

<hr>

<h3 class="text-center">Obrazy</h3>
<a href="{% url 'kadent:image_create_from_patient' object.id %}">
    <button class="btn btn-small btn-primary">Dodaj obraz do pacjenta</button>
</a>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">nazwa pliku</th>
            <th scope="col">dodany</th>
            <th scope="col">notatka</th>
            <th scope="col">dodany przez</th>
        </tr>
    </thead>
    <tbody>
        {% for image in images %}
        <tr>
            <td><a href="{% url 'kadent:image_edit' image.id %}">
                <img src="{{ image.thumbnail.url }}" alt="{{ image.filename }}" class="figure-img"> 
                </a>
            </td>
            <td><a href="{% url 'kadent:image_edit' image.id %}">{{ image.uploaded_at|date:'d.m.Y H:i' }}</a></td>
            <td><a href="{% url 'kadent:image_edit' image.id %}">{{ image.note }}</a></td>
            <td><a href="{% url 'kadent:image_edit' image.id %}">{{ image.uploaded_by }}</a></td>
        </tr>
        {% endfor %}

    </tbody>
</table>


{% endblock content %}

kadent/templates/kadent/visit_confirm_delete.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Potwierdź usunięcie wizyty pacjenta {{ object.patient }}, z dnia {{ object.timestamp }} 
        zapisanej przez: {{ object.doctor }}</p>
    <input type="submit" value="Potwierdzam">
</form>
{% endblock content %}

kadent/templates/kadent/visit_form.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}
<a href="{% url 'kadent:patient_edit' patient_id %}" class="float-right">
    <button class="btn btn-small btn-primary">Wróć do pacjenta</button>
</a>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>
{% endblock content %}

kadent/templates/kadent/visit_update_form.html
{% extends "kadent/base.html" %}
{% load static %}

{% block content %}

<h4 class="text-center">Pacjent: {{ object.patient }}</h4>
<h4>Wizyta u {{ object.doctor }}, {{ object.timestamp|date:'d.m.Y H:i' }}</h4>

<div class="row">
    <div class="col-lg-4">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Zapisz" class="btn btn-primary mb-2">
        </form>
    </div>
    <div class="col-lg-8">
        

        <div class="row justify-content-end">

            <div class="col-lg">
                <a href="{% url 'kadent:image_create_from_visit' object.id %}" class="float-left mb-3">
                    <button class="btn btn-small btn-primary">Dodaj obraz do tej wizyty</button>
                </a>
            </div>

            <div class="col-lg">
                <a href="{% url 'kadent:patient_edit' patient_id %}" class="float-right mb-3">
                    <button class="btn btn-small btn-primary">Wróć do pacjenta</button>
                </a>
            </div>
            <div class="w-100"></div>


            {% for i in images %}
                <div class="col-xl">
                    <a href="{% url 'kadent:image_edit' i.id %}">
                    <figure class="figure border">
                        <img src="{{ i.thumbnail.url }}" alt="{{ i.filename }}" class="figure-img">
                        <figcaption class="figure-caption text-center">
                            {{ i.filename }}
                            {% if i.note %}
                                <p>{{ i.note }}</p>
                            {% endif %}
                        </figcaption>
                    </figure>
                    </a>
                </div>

                {% if forloop.counter|divisibleby:"3" %}
                <div class="w-100"></div>
                {% endif %}

            {% endfor %}

        </div>



    </div>
</div>


{% endblock content %}